### ISSUE TITLE
PackageReference tests don't consider transitive dependencies

### ISSUE THREAD

**Issue by mattjohnsonpint** [SimonCropp/Polyfill#14]
The tests for various package references only consider directly referenced dependencies, not transitive ones.

For example, this checks if `System.Threading.Tasks.Extensions` is referenced:

https://github.com/SimonCropp/Polyfill/blob/8f862a423b2c65f8683f55f8f40bb7a5ffad6066/src/Polyfill/Polyfill.targets#L13-L14

If you've referenced it directly, then it works.  But if you get it via [dependency of `System.Text.Json`](https://www.nuget.org/packages/System.Text.Json/5.0.2#dependencies-body-tab), then it is not detected.

**Comment by mattjohnsonpint** [comment]
Same is true for `System.ValueTuple`, `System.Memory, etc.`

**Comment by mattjohnsonpint** [comment]
I can workaround for now by adding the references conditionally (as per your readme).  I can also use  `PrivateAssets="all"` on those, so they don't become direct dependencies on our nuget package.  (Users will get them transitively through System.Text.Json.)

**Comment by baronfel** [comment]
Try this to get the full list of direct and transitive PackageReferences used by the current project:

```xml
  <!-- Get the final resolved set of all packages -->
  <PropertyGroup>
    <!-- Need this to add your target to the overall build pipeline - 
        PrepareForBuild is a good general-purpose target for non-timing-critical tasks -->
    <PrepareForBuildDependsOn>$(PrepareForBuildDependsOn);PrintAllDeps</PrepareForBuildDependsOn>
  </PropertyGroup>
  <Target Name="PrintAllDeps" DependsOnTargets="ResolvePackageAssets">
    <!-- ResolvePackageAssets provides the resolved set of all packages in the `PackageDependencies` item list -->
    <Message Importance="High" Text="This project depends on the following exhaustive set of dependencies:" />
    <!-- This item is only the string name, no additional metadata, so for versions you might need to do more work -->
    <Message Importance="High" Text="@(PackageDependencies)" />
  </Target>
```

**Comment by mattjohnsonpint** [comment]
Also, my idea of adding them with `PrivateAssets="all"` doesn't work.  That stops them flowing transitively at all, even from the `System.Text.Json` reference.

So having this would be super helpful.  Thanks.

**Comment by Tyrrrz** [comment]
@baronfel is there a chance you could explain to an MSBuild idiot (i.e., myself), why is `PrepareForBuildDependsOn` required? Isn't `DependsOnTargets="ResolvePackageAssets"` already enough to add the task to the build pipeline?

**Comment by baronfel** [comment]
`DependsOnTargets` only comes into play when the target is actually going to be executed, so either you need to invoke the target directly (`dotnet build /t:MYTARGET`), or you need to cause your target to be a dependency of a target that is going to be run.

I chose the latter path, and based on what I knew of the problem I figured that your timing just needed to be
* after the dependencies had all been resolved, and
* before the build _sometime_

Based on that, I went with the good old standby, the `PrepareForBuild` target. This target is often used as a grab-bag of 'I'm not super timing sensitive' tasks. It's also very handy because its `DependsOnTargets` uses a Property to allow for extensibility. Hence the two-part pattern of

* adding to the `PrepareForBuildDependsOn` property so that our target is invoked when a `Build` target is run, and
* making sure that our target runs _after_ ResolvePackageAssets when our target is required to run at all

There are some detailed docs about the build order in general [here](https://learn.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2022) (including a specific ordering example), but we don't have a good set of examples for "you want to do action X, target Y is a good place for that".

**Comment by Tyrrrz** [comment]
> `DependsOnTargets` only comes into play when the target is actually going to be executed, so either you need to invoke the target directly (`dotnet build /t:MYTARGET`), or you need to cause your target to be a dependency of a target that is going to be run (for example `Build`, which is implicitly called by `dotnet build` and several other pathways).

Ah, right. I confused it with `AfterTargets` and `BeforeTargets`.

Would setting `BeforeTargets="PrepareForBuild"` work here?

**Comment by baronfel** [comment]
Not on its own - even if you specify `BeforeTargets="PrepareForBuild"` that only specifies a 'max bound'. So you'd still need `DependsOnTargets="ResolvePackageAssets"` as well. That means you could drop the `PrepareForBuildDependsOn` at least though!

**Comment by SimonCropp** [comment]
i probs wont get to this till tomorrow. if anyone wants to attempt a PR before then, that would be appreciated

**Comment by Tyrrrz** [comment]
@baronfel I just tested a bit and it seems that I could also use `@Reference`, which appears to return all assemblies referenced by the project (including package dependencies, netfx GAC references, and project references). What's the difference between `@Reference` and `@PackageDependencies`?

**Comment by SimonCropp** [comment]
thanks for all the help peoples.

Can you try v1.9.0

**Comment by baronfel** [comment]
@Tyrrrz looks like you found it out :) I'd also say that `Reference` items are too general - they can come from too many different sources. I'd generally prefer using a less-powerful, more specific Item.

**Comment by mattjohnsonpint** [comment]
It worked! Thanks!  I had an unrelated issue in updating to 1.9.0 though. See #19.  Thanks!
