### ISSUE TITLE
Consider adding `ArgumentNullException.ThrowIfNull(...)`

### ISSUE THREAD

**Issue by thomhurst** [SimonCropp/Polyfill#198]

**Comment by jcummings2** [comment]
For those of use finding it later, the historical link would have been to about commit bda3b35 like so:
https://github.com/SimonCropp/Polyfill/blob/bda3b351ab0f95a690dd3715e6304891c0d69048/readme.md#guard-1

I believe the correct section of the README now (commit d55fb17) is "Ensure" rather than "Guard" : https://github.com/SimonCropp/Polyfill?tab=readme-ov-file#ensure-1

However, I can't seem to get it to work by adding `<PolyEnsure>true</PolyEnsure>` in my project file. I'm also confused by the `ArgumentNullException` [references further up](https://github.com/SimonCropp/Polyfill/blob/main/readme.md#argumentnullexception) in the README. Those reference make me think it should just work directly until I noticed that those extension methods are on the `Polyfill` class. I do not, however, see those extension methods on `Polyfill`.

**Comment by SimonCropp** [comment]
@jcummings2 there are not extension methods. they are static method on Ensure
```
Ensure.NotNullOrEmpty
Ensure.NotNullOrWhiteSpace
Ensure.NotNull
```

**Comment by jcummings2** [comment]
Thank you for your reply.

I'm probably doing something wrong then because even with `<PolyEnsure>true</PolyEnsure>` in my project file, I cannot access those static methods. For reference, the entire section in my `.csproj` file is:

```csproj
    <PackageReference Include="Polyfill">
        <PolyEnsure>true</PolyEnsure>
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

**Comment by SimonCropp** [comment]
`<PolyEnsure>true</PolyEnsure>` should be in the properties of your project


```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net48</TargetFrameworks>
    <PolyEnsure>true</PolyEnsure>
  </PropertyGroup>
```

**Comment by jcummings2** [comment]
Thank you! Moving `<PolyEnsure>true</PolyEnsure>` there made the `Ensure` static methods available.

In case it got missed, I still find the [Extensions section in the main README](https://github.com/SimonCropp/Polyfill#extensions) to be confusing then. The extension methods listed there, at least the `ArgumentNullException` ones,  do not seem to exist at all. Did I miss another needed MSBuild property? Am I just misunderstanding what that list is? Or is that documentation outdated/wrong?
